### PR TITLE
Allow empty catalogs

### PR DESCRIPTION
**Pull request by jjrom**
**Related Issue(s):** #1115

**Proposed Changes:**

1. Remove the requirement that disallows empty catalogs. 

*Note: Said this is not a breaking change, as this is just relaxing a requirement, but could mark it as breaking if that is desired. It is a fairly major change, does require a new RC to be cut*

**PR Checklist:**

- [X] This PR is made against the dev branch (all proposed changes except releases should be against dev, not master).
- [x] This PR has **no** breaking changes.
- [x] I have added my changes to the [CHANGELOG](https://github.com/radiantearth/stac-spec/blob/dev/CHANGELOG.md)
      **or** a CHANGELOG entry is not required.

### CODE REVIEW

**Comment by cholmes** [comment]
@jjrom - this would be good to get in asap. The schema needs a bit more work, as does the wording. Would it be ok to collaborate directly on your branch on this?

**Comment by jjrom** [comment]
@cholmes Yes sure !

**Comment by cholmes** [comment]
Ok, I'm going to commit straight to your dev branch, as I think that is enabled.

**Review by cholmes — APPROVED** [review]
I updated this for the schema to reflect the intent (thanks @m-mohr for instructions on how) and also made it so it's recommended to have item or child, and touched on use cases when you may not.

**Comment by cholmes** [comment]
@jjrom - check the PR to make sure it still matches what you want.
@m-mohr - didn't end up doing best practice section, as it seems like it'd be a very short section, and wasn't sure where else it would fit in. And didn't seem bad to just fit it into the main spec. But I can try again if you don't think it's right there.

**Comment by jjrom** [comment]
@cholmes Yep it perfectly matches what i want :)

**Review by m-mohr — APPROVED** [review]

**Pull request merged**
