### PR TITLE
#302: Provider type to roles, string to array, added licensor, added descripion

### PR DESCRIPTION
**Pull request by m-mohr**
As discussed on Gitter and GitHub (#302).

We mostly agreed on type => role and the other changes are a proposal by me based on feedback from @mojodna that asks to allow specifying the licensor. And also, string was already flawed before, because a provider could be everything from the list of options.

### CODE REVIEW

**Comment by mojodna** [comment]
This makes total sense to me. I was originally thinking that keeping `licensor` closer to `license` would be nice, but both `license` and `providers` are required Collection properties.

**Comment by m-mohr** [comment]
The license url for license=proprietary is in links, so things get split anyway. Also in other cases, so I don't think that's a big problem.

**Comment by cholmes** [comment]
Discussed on call on 10/23 - @m-mohr to add 'description' here, for people to add in more information.

**Comment by m-mohr** [comment]
Added, please re-review it ;-) @cholmes @mojodna @matthewhanson

**Comment by matthewhanson** [comment]
re-reviewed, I think it's good to go

**Pull request merged**
