### PR TITLE
Allow asset specific band metadata

### PR DESCRIPTION
**Pull request by m-mohr**
As discussed yesterday, it is useful to allow asset specific band metadata, for example for the new extension "EO for processing and ingestion" (eop), which will add unit, scale and offset as asset specific metadata. This is currently not possible, but I think it is helpful to allow this generally in the EO extension.

This PR is meant to discuss the need and potential solutions, with me preferring this solution. Bases on PR #245 and may potentially be used for issues #243, #242 and the gain/scale, offset, unit addtions for eop, which have no separate issue.

**PR Checklist:**

- [ ] This PR has **no** breaking changes.
- [ ] I have added my changes to the [CHANGELOG](https://github.com/radiantearth/stac-spec/blob/dev/CHANGELOG.md) **or** a CHANGELOG entry is not required.
- [ ] API only: I have run `npm run generate-all`. to update the [generated OpenAPI files](https://github.com/radiantearth/stac-spec/blob/dev/api-spec/README.md#openapi-definitions).

### CODE REVIEW

**Comment by hgs-truthe01** [comment]
I'm still confused on why we want to put metadata in the assets section? Any metadata outside of properties breaks the common metadata model. If you put the unit scale and offset values in properties["eo:bands"] what won't you be able to do? I'm pretty uncomfortable with having some metadata in properties and some in assets.

**Comment by m-mohr** [comment]
@hgs-truthe01 After thinking about this again for a while, this actually might not be required any longer due to that fact that we changed from dicts to arrays.
But let me first ask you how you would solve this at the moment:
You have a STAC item with two assets, both have bands that share the same names and basically the same characteristics, but differ in two values such as scale and offset. How would you model that? That's basically the use case that came up previously in a discussion with @matthewhanson and @fredliporace.

**Comment by matthewhanson** [comment]
@hgs-truthe01 
The problem as @m-mohr mentions is that you can have values that vary by asset and item.

For example, with Landsat there is a scale and offset given for each band, see here:
https://landsat-pds.s3.amazonaws.com/c1/L8/086/240/LC08_L1GT_086240_20180827_20180827_01_RT/index.html
Scroll down to RADIOMETRIC_RESCALING and you'll see RADIANCE_MULT_BAND_X and RADIANCE_ADD_BAND_X, along with values for converting to REFLECTANCE as well.

With Landsat-8 it's true that these values are constant across all assets, but that was not always the case. Landsat-7 and earlier have values for scaling that change for each asset. I've also seen this occur in other data sources as well, so it's not limited to Landsat.

**Comment by hgs-truthe01** [comment]
Another question I think needs to be resolved. Is this a valid item:

```
{
  "assets" :{
    "B1": {
      "href": "http://landsat-pds.s3.amazonaws.com/L8/153/025/LC81530252014153LGN00/LC81530252014153LGN00_B1.TIF",
      "type": "GeoTIFF",
      "required": true,
      "eo:bands": [
        {
          "index": 0,
          "gsd": 15
        }
      ]
    }
  },

  "eo:bands": [
    {
      
      "name": "1",
      "common_name": "coastal",
      "gsd": 30.0,
      "accuracy": null,
      "wavelength": 0.44,
      "full_width_half_max": 0.02
    }
  ]
]
}
```

Why would we put specific eo fields in one place or the other? What happens if they are in both places?

**Comment by hgs-truthe01** [comment]
So, the fact that gsd isn't allowed in assets is exactly the "special" rules that I was trying to avoid with the common metadata model.

I think what you are asking for here is essentially a deep merge on eo:bands between item and asset levels. But with rules on what fields go where.

What I would propose is that we don't have special rules and we make use of the commons extension. This might require a small change to commons extension to say that we should use a deep merge when applying common properties though.

collection level:
```
{
  "properties": {
    "eo:bands": [
        {
          "center_wavelength": 700,
          "gsd": 15,
          ...
        }
      ]
}
```

item level:
```
{
  "properties": {
    "c:id": 
    "eo:bands": [
        {
          "offset":10,
        }
      ]
}
```

I think this would solve the use case you are describing, but if there really is asset specific metadata, then I would suggest we need to add assets[0].properties and follow the same rules as the commons from collections to items to assets.

**Comment by matthewhanson** [comment]
That doesn't quite do it either @hgs-truthe01  because  you could have an two different assets that reference the same spectral band, but with different scales and offsets.

Case in point again is Landsat, which has one set of scale/offset to get the into Reflectance, and and another scale/offset to get the data in Radiance. These could be two different assets but both reference the same spectral band.

In a similar fashion you might have the actual data file which contains RGB and requires scale/offset to get into TOA reflectance, and then a true color image which also contains RGB but doesn't have scale of offset because the values have already been scaled to a byte.

I definitely would like to use behavior like in the Commons extension do be able to handle this. Because sometimes you might have to specify these fields per asset, and other times they will be the same for the same asset across all Items. But what we're talking about really isn't band specific information though, it really needs to be tied to the assets.

I'd like to wait on this until the next release when we work on an asset definition, I don't feel comfortable pushing this into this release because I think there's still plenty to discuss.

**Comment by m-mohr** [comment]
> What I would propose is that we don't have special rules and we make use of the commons extension. This might require a small change to commons extension to say that we should use a deep merge when applying common properties though.
> [...]
> I think this would solve the use case you are describing, but if there really is asset specific metadata, then I would suggest we need to add assets[0].properties and follow the same rules as the commons from collections to items to assets.

This sounds reasonable, but also a bit complex. In the end this means that for example you can have a datetime per asset for example and having multiple of them would lead to a daterange in the Item etc.

> I'd like to wait on this until the next release when we work on an asset definition, I don't feel comfortable pushing this into this release because I think there's still plenty to discuss.

Sounds good to skip this for 0.6.0 - leads to us changing the bands and assets in multiple versions drastically, but it's a 0.x version, right? ;-)

**Comment by hgs-truthe01** [comment]
I'm also on board for a 0.7 discussion on this.

>  This really isn't band specific information
That says to me we shouldn't put it in an eo:bands key right?

**Comment by cholmes** [comment]
Moved to 0.8.0, as asset definition stuff is going there.

**Comment by matthewhanson** [comment]
Talked about this in meeting, and discussed how there hasn't seemed to be anyone with a compelling use case that is driving this anymore. We are closing this for now, and can revisit the issue if there are future use cases that come up.

**Pull request closed without merging**
