### PR TITLE
Add processing to extension list

### PR DESCRIPTION
**Pull request by m-mohr**
**Related Issue(s):** #907 

**Proposed Changes:**

1. We forgot to add the processing extension to the extension README

**PR Checklist:**

- [x] This PR is made against the dev branch (all proposed changes except releases should be against dev, not master).
- [x] This PR has **no** breaking changes.
- [x] I have added my changes to the [CHANGELOG](https://github.com/radiantearth/stac-spec/blob/dev/CHANGELOG.md) **or** a CHANGELOG entry is not required.
- [ ] This PR affects the [STAC API spec](https://github.com/radiantearth/stac-api-spec), and I have opened issue/PR #XXX to track the change.

### CODE REVIEW

**Review by cholmes — APPROVED** [review]

**Comment by jisantuc** [comment]
Are there any artifacts of the processing extension? I don't see anything in the repo

**Comment by cholmes** [comment]
@jisantuc - it just merged to dev - https://github.com/radiantearth/stac-spec/tree/dev/extensions/processing

**Comment by m-mohr** [comment]
@jisantuc You probably looked at master (made the mistake myself today). Have a look at dev :-)

**Comment by jisantuc** [comment]
_every single time_

**Review by jisantuc — APPROVED** [review]

**Pull request merged**
