### PR TITLE
Restored UML diagram

### PR DESCRIPTION
**Pull request by hgs-msmith**
Updated to spec version 1.0.0

**Related Issue(s):** #1030 

**Proposed Changes:**

1. Updated to spec version 1.0.0
2. 

**PR Checklist:**

- [x] This PR is made against the dev branch (all proposed changes except releases should be against dev, not master).
- [x] This PR has **no** breaking changes.
- [ ] I have added my changes to the [CHANGELOG](https://github.com/radiantearth/stac-spec/blob/dev/CHANGELOG.md) **or** a CHANGELOG entry is not required.
- [ ] This PR affects the [STAC API spec](https://github.com/radiantearth/stac-api-spec), and I have opened issue/PR #XXX to track the change.

### CODE REVIEW

**Review by matthewhanson — APPROVED** [review]

**Comment by cholmes** [comment]
@hgs-msmith - one of the changes we made in 1.0.0-rc.1 is that collection no longer inherits from catalog. Could you update the UML so it doesn't have that relationship?

**Comment by philvarner** [comment]
After the mtg this morning, it dawned on me what the problem is and what the relation is:

* Catalog and Collection have a has-a relationship -- a Catalog has-a zero-or-more Collections.  
* Collection is **NOT** a Catalog (is-a)
* Collection and Catalog both is-a (are-a?) "STAC Aggregate" -- they both relate together other object (a Collection relates together other Collections and Items; a Catalog relates together other Catalogs, Collections, and Items). Aggregate is probably a bad term to use here b/c it's too easy to get confused with SQL-like aggregation functions **instead** of having the domain-driven design meaning. 
* I think it's actually simpler just to say they're two types not related by subtying, but happen to have several fields that are named the same.

**Comment by hgs-msmith** [comment]
Updated UML diagram to remove inheritance relationship between Collection and Catalog.

**Review by m-mohr — CHANGES_REQUESTED** [review]
Thanks Michael, here are some suggestions for improvements:
- Items can also link to collections with rel types root and parent.
- The note about the extensions can be removed or shortened ("Note: This diagram does not contain extensions.") as we are going to remove all extensions from core.
- link:rel=child is 0..* in catalogs and 0..1 in collections. I think it should be 0..* in both.

**Review by m-mohr — APPROVED** [review]

**Pull request merged**
