### PR TITLE
Add palette asset role

### PR DESCRIPTION
**Pull request by zakjan**
**Related Issue(s):** https://github.com/stac-extensions/raster/issues/17

**Proposed Changes:**

1. Add palette asset role

**PR Checklist:**

- [x] This PR is made against the dev branch (all proposed changes except releases should be against dev, not master).
- [x] This PR has **no** breaking changes.
- [x] I have added my changes to the [CHANGELOG](https://github.com/radiantearth/stac-spec/blob/dev/CHANGELOG.md)
      **or** a CHANGELOG entry is not required.
- [ ] This PR affects the [STAC API spec](https://github.com/radiantearth/stac-api-spec),
      and I have opened issue/PR #XXX to track the change.

### CODE REVIEW

**Comment by zakjan** [comment]
Searching for references about color palette files in other tools, it seems there is no common standard or MIME type. I'm not sure whether the palette asset role can recommend a particular format or a library to parse it, so I haven't included it yet. @cholmes What do you think?

The largest collection of color palettes [cpt-city](http://soliton.vm.bytemark.co.uk/pub/cpt-city/) provides palettes in 11 different formats. GDAL-compatible format seems safe to recommend. Some formats can be converted using [cptutils](http://soliton.vm.bytemark.co.uk/pub/jjg/en/code/cptutils/).

**Comment by zakjan** [comment]
Found [download stats by format](http://soliton.vm.bytemark.co.uk/pub/cpt-city/stats/formats.html)! So it's `cpt` the most used indeed.

**Comment by m-mohr** [comment]
Would this make more sense to be added to the raster extension instead?

**Comment by m-mohr** [comment]
@zakjan Do you still plan to open a PR for this in the raster and/or classification extensions?

**Comment by zakjan** [comment]
Hi @m-mohr, I'm sorry for inactivity, I'm totally swamped these days :( Have you seen any interest about this topic from anyone else?

**Comment by m-mohr** [comment]
@zakjan Unfortunately not so much, so take your time, I guess....

**Comment by m-mohr** [comment]
It's so funny how like 30mins after you closed this, someone asked me about it. I forwarded this link, so maybe someone will chime in soon.

**Comment by zakjan** [comment]
Haha :) Anyway, this is only about standardizing a STAC field if there is more interest about it. Anyone can still use it as a custom field.

Regarding the implementation, I've implemented https://github.com/weatherlayers/cpt2js for parsing the palette files.

**Pull request closed without merging**
