### PR TITLE
Typos and minor edits -- dev

### PR DESCRIPTION
**Pull request by ymoisan**
Replaces PR 871.

**Related Issue(s):** #

**Proposed Changes:**

1. 
2. 

**PR Checklist:**

- [ ] This PR is made against the dev branch (all proposed changes except releases should be against dev, not master).
- [ ] This PR has **no** breaking changes.
- [ ] I have added my changes to the [CHANGELOG](https://github.com/radiantearth/stac-spec/blob/dev/CHANGELOG.md) **or** a CHANGELOG entry is not required.
- [ ] This PR affects the [STAC API spec](https://github.com/radiantearth/stac-api-spec), and I have opened issue/PR #XXX to track the change.

### CODE REVIEW

**Comment by m-mohr** [comment]
Thank you, I must admit I don't like all the whitespace changes, which may lead us into merge conflicts and thus I'm hesistant to approve this...

**Comment by ymoisan** [comment]
@m-mohr I agree this is quite bothersome.  Let me check if I can make things better in my editor settings (Atom).

**Comment by cholmes** [comment]
@ymoisan - any word on the whitespace stuff? Agree it'll help with a cleaner PR, and it'd be great to get these edits in.

**Comment by ymoisan** [comment]
@cholmes I'm fighting with Atom on that.  Such a drag.  Let me try and push something later this week.  Thanx for following up ...

**Comment by m-mohr** [comment]
Easiest could probably be to just re-do the PR with another Editor ;-)

**Comment by ymoisan** [comment]
@m-mohr good old gedit made things less bad but it's still not perfect.  OK with you or you want me to try *real* hard :-) ?

**Review by m-mohr — APPROVED** [review]

**Comment by m-mohr** [comment]
No, thank you for taking the effort, that looks pretty good now. Approved and merged!

**Pull request merged**
