### PR TITLE
Sar updates

### PR DESCRIPTION
**Pull request by matthewhanson**
**Related Issue(s):** #
#619

**Proposed Changes:**

1. change `sar:type` to `sar:product`
2. move `sar:bands` attributes into assets

**PR Checklist:**

- [ ] This PR has **no** breaking changes.
- [x] I have added my changes to the [CHANGELOG](https://github.com/radiantearth/stac-spec/blob/dev/CHANGELOG.md) **or** a CHANGELOG entry is not required.
- [ ] API only: I have run `npm run generate-all` to update the [generated OpenAPI files](https://github.com/radiantearth/stac-spec/blob/dev/api-spec/README.md#openapi-definitions).

### CODE REVIEW

**Comment by matthewhanson** [comment]
@m-mohr This removes `sar:center_wavelength`, moves `sar:type` to `sar:product`

I've also moved `sar:bands` into assets which we can discuss, I did not update the schema yet but wanted to show an example. It drops the description field because it's not specific to SAR, and we might consider adding it to the assets.   The other fields: `data_type`, `unit`, and `polarization` definitely vary by asset, and in fact `band` is actually not a great name for these terms because `data_type` and `unit` arise from processing, not how the data is collected like with eo:bands.

**Comment by m-mohr** [comment]
* I'm not yet convinced that it's really a good idea to remove sar:center_wavelength (or sar:center_frequency) as they are more specific as sar:frequency_band.
* Fine with renaming type to product or product_type. Just thinking, but would that be a field which also applies to EO (with a different set of values)?
* As with the bands for EO, I'm not yet sure I like the bands in the assets. But that's a discussion to be held in a bigger group anyway and until then we shouldn't change it.

**Comment by matthewhanson** [comment]
This only has sar:center_wavelength being removed, it's kinda redundant having both since you can calculate one from the other based on the medium the waves are traveling through.

I do think product is a rather general term that could be useful for other types of data.  For EO it might be Radiance, TOA, Surface Reflectance, etc.

**Comment by matthewhanson** [comment]
The more I think about the bands here the more I think that both `data_type` and `processing` are general asset level metadata fields.  I don't see how they fit along with polarizations at all, they have to do with how the data is processed, not how it is collected.

Once you remove those fields from `sar:bands`, and `description` which is certainly general - then all you have left is the polarization which seems silly to have to reference from the assets.

```
'myasset': {
    "polarizations": ["HH"]
}
```
OR

```
'sar:bands': [
   {
       "name": "HH",
       "polarization": "HH"
   }
]
---
'myasset': {
    "polarizations": [0]
}
```

**Pull request closed without merging**
