### PR TITLE
Backporting WFS3 draft 2 to STAC

### PR DESCRIPTION
**Pull request by m-mohr**
Tackles #472, partly #517 and #512.

Therefore, updates WFS3 OpenAPI file, updates API documentation and backports (a subset of) changes to STAC collections. This restores compatibility with the latest draft of WFS3 (aka OGC API - Features - Part 1: Core) as released here: https://github.com/opengeospatial/WFS_FES/releases/tag/1.0.0-draft.2

Notes:
* Several API query parameters changed significantly (e.g. `datetime`). ~~We are currently diverging here (`time` vs `datetime`).~~ I tried to fix the API examples, but please check carefully. ~~Open question: should we align? See #517~~ (Edit: I removed `time` so we are now aligned with WFS. See comments below.)
* ~~In addition to the WFS3 backporting I changed the following sentence in the API spec from `Either a date-time or a period string that adheres to RFC3339.` to `Either a date-time that adheres to RFC3339 or a period string that adheres to ISO8601.` RFC3339 doesn't specify period strings.~~ (Edit: Not relevant any longer after removing the `time` parameter.)
* Merging STAC and WFS OpenAPI files lead to a mal-formed OpenAPI file, therefore un-commented some required fields in the WFS YAML . They are also required in STAC, so that's not a problem.
* WFS links have additional properties `hreflang` and `length`, which are optionally available in the API, but were not ported back to STAC Items/Catalogs/Collections (see https://github.com/radiantearth/stac-spec/issues/472#issuecomment-511880235)
*  Also, I haven't backported the optional fields `crs` and `itemType` to STAC Collections (see https://github.com/radiantearth/stac-spec/issues/472#issuecomment-511880235)
* Extents have changed in STAC Collections. I did not backport `trs` and `crs` in the extents as WFS3 only allows a single value and defaults to it. Therefore, we can simply ignore it and force all values to comply to these defaults (WGS84 / Gregorian Calender).
* I found some issues in the WFS draft which make the OpenAPI file unsuable and reported these issues to Clemens Portele. Those issues are already solved here, but will only be part of the next WFS release. See https://github.com/opengeospatial/WFS_FES/commit/1cd3549a84066885faf837a99cb17fa682606a43 and https://github.com/opengeospatial/WFS_FES/commit/d1fbe39b61054606be59bc94e2965d93dbb03a0a
* This PR also contains some fixes for invalid Collection examples
* For pagination they have `numberMatched` and `numberReturned` as well as links to support paging (link relation next). We diverge from this with our extension. Should we align?

**PR Checklist:**

- [ ] This PR has **no** breaking changes.
- [x] I have added my changes to the [CHANGELOG](https://github.com/radiantearth/stac-spec/blob/dev/CHANGELOG.md) **or** a CHANGELOG entry is not required.
- [x] API only: I have run `npm run generate-all`. to update the [generated OpenAPI files](https://github.com/radiantearth/stac-spec/blob/dev/api-spec/README.md#openapi-definitions).

### CODE REVIEW

**Comment by philvarner** [comment]
> Several API query parameters changed significantly (e.g. datetime). We are currently diverging here (time vs datetime). I tried to fix the API examples, but please check carefully. Open question: should we align? See #517

I would like us to get rid of `time` and only have the `datetime` parameter, and with the same definition as in WFS.  While it might be nice to allow different formats and expressions, I don't think the added capability outweighs the additional required implementation burden.

**Comment by philvarner** [comment]
In addition to the WFS3 backporting I changed the following sentence in the API spec from Either a date-time or a period string that adheres to RFC3339. to Either a date-time that adheres to RFC3339 or a period string that adheres to ISO8601. RFC3339 doesn't specify period strings.

I don't know what a period string is.  I would prefer we only support RFC3339 as WFS 3 does, unless there's a compelling reason to support the ISO8601 ones also.

**Comment by philvarner** [comment]
> For pagination they have numberMatched and numberReturned as well as links to support paging (link relation next). We diverge from this with our extension. Should we align?

Links to support paging become problematic when you could possibly submit a multi-megabyte GeoJSON string as a parameter, hence our `next` parameter and `search:metadata.next` field.

**Comment by philvarner** [comment]
> For pagination they have numberMatched and numberReturned as well as links to support paging (link relation next). We diverge from this with our extension. Should we align?

I think we should make them `numberMatched` and `numberReturned` to align.

**Comment by m-mohr** [comment]
@philvarner Thanks for the review.

> I would like us to get rid of `time` and only have the `datetime` parameter, and with the same definition as in WFS.

Fine for me, was proposing this to address concerns raised by @matthewhanson. What do you think, Matt?


> I don't know what a period string is. I would prefer we only support RFC3339 as WFS 3 does, unless there's a compelling reason to support the ISO8601 ones also.

WFS defines the period strings itself (with another name). RFC3339 only defines a single instance in time and therefore, WFS took the notion for intervals (here: period strings) from ISO8601, including the two dots for open intervals. So I guess we should align to the WFS terms here, but we can't really get rid of ISO8601. 

> Links to support paging become problematic when you could possibly submit a multi-megabyte GeoJSON string as a parameter, hence our `next` parameter and `search:metadata.next` field.

I don't get that. Isn't that more or less the same? Can't you simply generate the link with our next token and add it to the links?

**Comment by m-mohr** [comment]
I removed the `time` parameter for now (related discussions also in #521 and #536). If we decide to add `date` again, we can do that in another PR, I think. I have opened issue #536 to streamline the discussions whether we want a date parameter or not.

**Comment by philvarner** [comment]
Are the period strings the interval syntax, `2019-07-22T00:00:00/..`? If not, can you show me an example?

**Comment by m-mohr** [comment]
> Are the period strings the interval syntax, `2019-07-22T00:00:00/..`? If not, can you show me an example?

Yes, period string = interval syntax. "period string" is not in the API specification any longer, we use the WFS description now.

**Comment by philvarner** [comment]
>> Links to support paging become problematic when you could possibly submit a multi-megabyte ? 
>> GeoJSON string as a parameter, hence our next parameter and search:metadata.next field.

> I don't get that. Isn't that more or less the same? Can't you simply generate the link with our next 
> token and add it to the links? @philvarner

You could do that, but then it's misleading because it's only part of the url for the next page.  For example, the url `https://example.com/stac/search?geometry={1mb geojson}` would mean that you either set the `next` link value to `https://example.com/stac/search?geometry={1mb geojson}&next=some_token` or `https://example.com/stac/search?next=some_token`, the first of which is intolerably large and the second of which is only part of the URL required to the the next page of results, but with no indication that that's the case. WFS 3 doesn't have this problem because none of the parameters to their GET endpoint are likely to have large values, like our `geometry` parameter can.

That's why we settled on semantics whereby the response has a `search:metadata.next` value, and the client is responsible for constructing the next query for the next page of results with that value set as the value of the `next` parameter.

**Comment by m-mohr** [comment]
@philvarner Thanks for the clarification. Then I don't see a good reason to align paging and/or search metadata, I think.

**Comment by philvarner** [comment]
> For pagination they have numberMatched and numberReturned as well as links to support paging (link relation next). We diverge from this with our extension. Should we align?

An underlying issue with this is that if we decide to align (which I believe we should), we're going to need to introduce fields with camelCase.  I feel that if getting parts of STAC adopted WFS/OGC is an objective of this project, then we should do as much as possible to align our naming scheme with those specs, even if some people may not like camelCase.

**Comment by m-mohr** [comment]
We are in dependency hell here. openEO API uses STAC, too, and that is also using snake_case to be aligned. We could do it together with #357, if we do it. But just for aligning this little bit, I wouldn't do all the work just for aligning casing. Anyway, this is a completely different topic. ;-)

**Comment by matthewhanson** [comment]
This looks good - totally on board with `datetime` as I always hated the `time` parameter and happy that WFS3 changed it.

**Comment by m-mohr** [comment]
STAC Working Session Notes:

> * Several API query parameters changed significantly (e.g. `datetime`). ~We are currently diverging here (`time` vs `datetime`).~ I tried to fix the API examples, but please check carefully. ~Open question: should we align? See #517~ (Edit: I removed `time` so we are now aligned with WFS. See comments below.)

Align with datetime. We may add a date query parameter in an extension if required.


> * For pagination they have `numberMatched` and `numberReturned` as well as links to support paging (link relation next). We diverge from this with our extension. Should we align?

Don't align at the moment.

**Pull request merged**
