### PR TITLE
Asset rel field for purpose

### PR DESCRIPTION
**Pull request by philvarner**
**Related Issue(s):**  n/a

**Proposed Changes:**

1. add a field `rel` to Asset to be used for the purpose of the asset, similarly to `rel` in Link

**PR Checklist:**

- [X] This PR has **no** breaking changes.
- [X] I have added my changes to the [CHANGELOG](https://github.com/radiantearth/stac-spec/blob/dev/CHANGELOG.md) **or** a CHANGELOG entry is not required.
- [X] API only: I have run `npm run generate-all` to update the [generated OpenAPI files](https://github.com/radiantearth/stac-spec/blob/dev/api-spec/README.md#openapi-definitions).

### CODE REVIEW

**Comment by jjrom** [comment]
Why not call it rel if it's similar to rel in link ?

**Comment by philvarner** [comment]
> Why not call it rel if it's similar to rel in link ?

I think that's fine -- I thought there was some desire to have it named something that didn't mean 'relation'.

**Comment by m-mohr** [comment]
We discussed this in a small group and think also purpose is not good, but rel is good neither. With rel we always refer to the IANA relation type list in the docs and that list lists nothing that is really useful for assets. So it's not really rel and I wouldn't explain the field with as being similar to rel. Maybe it's better to name it "role" and have a better description what it should be use for.

**Comment by philvarner** [comment]
`role` sounds good to me. Could be confused with permissions.

**Comment by m-mohr** [comment]
Indeed, although you'd usually not see it standalone. Either it would be for example `role=thumbnail` and then the values explains that it's not about permissions. Or you'd see it in docs and there's an explanation coming with it. Anyway, it's bike-shedding and doesn't make me not approve this PR. 

Oh, I just realized: PR is against master, not dev.

**Comment by philvarner** [comment]
https://github.com/radiantearth/stac-spec/pull/651

**Pull request closed without merging**
