### PR TITLE
Fix typo in Item Specification bbox description

### PR DESCRIPTION
**Pull request by whistler**
A bounding box cannot be defined by four numbers without specifying the right most coordinate. Fixing typo to use the top right corner instead of top left. This is consistent with how GeoJSON defines bbox, lowest coordinate values first followed by highest coordinate values.

### CODE REVIEW

**Comment by m-mohr** [comment]
Thanks a lot, unbelievable that nobody found this mistake until now.

**Comment by cholmes** [comment]
Going to shift this to merge to dev, and we can cherry pick to master when we do a 0.6.2 release.

**Comment by m-mohr** [comment]
Yes, this must go towards dev, nor master.

**Comment by whistler** [comment]
I have removed the extra commits from this branch and switched the pull request to merge into dev.

**Pull request merged**
