### PR TITLE
adjusted required assets extension fields to agree with json-schema

### PR DESCRIPTION
**Pull request by anayeaye**
**Related Issue(s):** #
N/A

**Proposed Changes:**
1. The `Asset Object` fields in the `assets` Collection extension did not reflect the required fields in the json-schema
2. Change not made: `type` is required for `Asset Object`s in the Collection extension but not in Items. Do we want to remove the type field requirement for Collection-Item agreement and/or open an issue to discuss?

**PR Checklist:**

- [x] This PR has **no** breaking changes.
- [ ] I have added my changes to the [CHANGELOG](https://github.com/radiantearth/stac-spec/blob/dev/CHANGELOG.md) **or** a CHANGELOG entry is not required.
- [x] ~~API only: I have run `npm run generate-all` to update the [generated OpenAPI files](https://github.com/radiantearth/stac-spec/blob/dev/api-spec/README.md#openapi-definitions).~~

### CODE REVIEW

**Comment by m-mohr** [comment]
Aligning JSON schema and the documentation is good, but I'm wondering whether the schema is actually correct? I understand that there should be something valuable in the asset, but the item spec itself only requires `href`. What if I just want to specify roles and type for example? @matthewhanson How was that meant to be?

**Comment by anayeaye** [comment]
I am also in favor of having more flexibility with which asset fields to implement.

**Comment by m-mohr** [comment]
We could set the `minProperties` to 1 or 2...

**Comment by matthewhanson** [comment]
I agree that title and type probably should not be required.

**Comment by cholmes** [comment]
What's the status of this with all the recent moves? Is it ready to be reviewed / merge in?

**Comment by m-mohr** [comment]
No, the points above still need to be changed.

**Comment by m-mohr** [comment]
As this PR has a heavy merge conflict due to the item asset rename, I also have some fixes in PR #797 and this minProperties thing is still in discussion (I opened issue #799 to keep treck), I'd think we can close this and make a new PR once we have consensus on #799. Do you agree, @anayeaye ?

**Pull request closed without merging**
