### PR TITLE
updated boundless links

### PR DESCRIPTION
**Pull request by joshfix**

### CODE REVIEW

**Comment by cholmes** [comment]
@joshfix - welcome back!

Lots of good stuff discussed at STAC sprint, I owe the world a write up on all we discussed. Some decent sized shifts on the API side, but I think they're all quite good. #172 in particular lets us bridge api and static catalogs in a nice way (if it's confusing just wait for my write up). 

We're shifting to 2 reviewers to merge, and we've got some CI integrated to do checks on merges.

**Comment by cholmes** [comment]
Ah, should be dev. I tend to just change the PR's to go to dev, as I assume people just forget to adjust - unless they explicitly say 'this is for master'.

**Comment by joshfix** [comment]
Hey thanks everybody.  I quickly applied some of the big changes we settled on after the Ft. Collins meet up, but I know I didn't cover all the bases.  Sorry I couldn't make this last meet up.  As soon as I get a chance to see what's new in 0.6.0 I'll make sure our implementation gets updated.

**Comment by m-mohr** [comment]
Approved the change, can be merged @cholmes. I think the "update branch" button merged our dev changes to the master branch of @joshfix . Was not aware of that (but is logical now that I see it). Sorry about that, but otherwise we would had to re-do the whole PR anyway.

**Comment by cholmes** [comment]
No worries on missing the last sprint @joshfix - I think we made lots of good progress. Would be great if you have time to give a read through on 0.6.0-RC1, in case we did anything egregious.

**Pull request merged**
