### PR TITLE
Add required properties to Item JSON schema

### PR DESCRIPTION
**Pull request by mojodna**
`geometry`, `bbox`, and `properties` are required properties per https://github.com/radiantearth/stac-spec/blob/master/item-spec/item-spec.md#item-fields

### CODE REVIEW

**Comment by cholmes** [comment]
Between this and #380 we should probably do a 0.6.2

Is there a good way to remember to merge this into dev as well?

**Comment by m-mohr** [comment]
I'd merge this to dev rather than master and have a separate branch 0.6.2 where we cherry picking anything that we think could go into 0.6.2. (Or the other way round.)

**Comment by matthewhanson** [comment]
@mojodna We talked about in meeting this morning, can you close and create new PR to develop?

**Comment by m-mohr** [comment]
Tried to update the branch to merge it to dev, but due to an outdated dev-branch (missing changes for 0.6.1) this needs #390 to be merged first!

**Comment by mojodna** [comment]
@matthewhanson @m-mohr I've been busy elsewhere this week; thanks for tackling this and getting it merged!!

**Pull request merged**
