### PR TITLE
Move eobands to collection

### PR DESCRIPTION
**Pull request by matthewhanson**
**Related Issue(s):** #
#762 

**Proposed Changes:**

This moves eo:bands from being an Item property to the Collection level only (top-level).
eo:bands was not searchable, being a nested object, and being at the Item level lent itself to potentially a lot of unnecessary duplication.

**PR Checklist:**

- [x] This PR is made against the dev branch (all proposed changes except releases should be against dev, not master).
- [ ] This PR has **no** breaking changes.
- [x] I have added my changes to the [CHANGELOG](https://github.com/radiantearth/stac-spec/blob/dev/CHANGELOG.md) **or** a CHANGELOG entry is not required.
- [ ] This PR affects the [STAC API spec](https://github.com/radiantearth/stac-api-spec), and I have opened issue/PR #XXX to track the change.

### CODE REVIEW

**Comment by m-mohr** [comment]
In principle, I like the change, but there are some things we should think about:
* We've seen EO as pretty stable and it's pretty commonly used. So I think we should survey some more users than the usual reviewers whether this changes is fine for most.
* How would a "single item" with bands in a single file look like? I have a use case where we respond to processing requests in our HTTP API with a single item and this change would lead us to some drastic changes, I guess?!
* Having bands and "band references" (this array indices pointing to the bands in the assets) in separate files makes them even more fragile to errors, I think (at least if you haven't used commons before). If you change something in the Collection, you must somehow ensure that all your Items are also updated whereas before it was just integrity you had to ensure for a single file.

**Comment by m-mohr** [comment]
A general question: As we are moving the "complex" structure out of the Items, is that basically a "best practice" for extensions with "complex structures" to put them in Collections?

**Comment by matthewhanson** [comment]
I think the best practice is "don't use complex objects" in Item properties, and instead separate them out into individual fields.

However, we do use complex objects at the Item and Collection level, but always (well, if we move eo:bands out) at the top-level, not in the properties.

So I think the general recommendation is complex structure never in properties, and instead put the in the top level, then on the API side consider supporting the querying of those with new query parameters.


ugh, looks like I've got some merge conflicts to work through

**Comment by m-mohr** [comment]
I'm wondering whether it could make sense to put eo:bands in summaries? Then there's a central place for collection metadata and it may be easier to index/search on collection metadata at some point. (I'm actually thinking to do a "worldwide" STAC collection index at some point to experiment with collection-level search...)

**Comment by matthewhanson** [comment]
Summaries are defined as being a summary of what is present in the Item properties. Since eo:bands is not in the Item properties this seems strange, it wouldn't be working like everything else in summaries. It would also be a dictionary quite unlike the stats objects that we see in summaries.

**Comment by jjrom** [comment]
> So I think the general recommendation is complex structure never in properties, and instead put the in the top level, then on the API side consider supporting the querying of those with new query parameters.

I don't see why complex structure - or any other item metadata property - should be put at the top level of the item. The big advantage to keep it within properties block is that any GeoJSON reader will display it which is not the case if you move it at the top level

**Comment by m-mohr** [comment]
> Summaries are defined as being a summary of what is present in the Item properties.

Yes and no... Summaries have a focus on that, but are not restricted to that. Otherwise we couldn't put any data in there for Collections without Items. So they could also contain bands. 

> It would also be a dictionary quite unlike the stats objects that we see in summaries.

No, bands is an array! As such it would have exactly the same schema as it is defined now.

> I don't see why complex structure - or any other item metadata property - should be put at the top level of the item. The big advantage to keep it within properties block is that any GeoJSON reader will display it which is not the case if you move it at the top level

I agree with that.

**Comment by matthewhanson** [comment]
Doh! Right, an array - wishful thinking on my part.

Well, I'm fine with moving it to summaries if I get some agreement on it, I can update the PR tonight.

**Comment by jbants** [comment]
+1 on summaries. 

@m-mohr for your single item use case, could you use the single-file stac extension?

**Comment by m-mohr** [comment]
> @m-mohr for your single item use case, could you use the single-file stac extension?

@jbants Yes, in theory I could. In practice the extension just blows up your JSON structure to a degree that I'm not willing to push that. It's like breaking a butterfly on a wheel. Then I'm more likely to not implement STAC at all for that endpoint or just go with collection-level assets (#779).

**Comment by m-mohr** [comment]
There's another idea for bands in this PR: https://github.com/radiantearth/stac-spec/pull/786#discussion_r416440166

Bands could also be part of the asset definition in collections.

**Comment by matthewhanson** [comment]
Ok, will redo PR to put into summaries...

**Comment by matthewhanson** [comment]
Strike that, based on discussion in #786 going to consider moving to asset definition instead.

**Comment by matthewhanson** [comment]
Closing this, see summary of discussion here: https://github.com/radiantearth/stac-spec/issues/762#issuecomment-621294872

**Pull request closed without merging**
