### PR TITLE
Fixing #146. Changing dateTime to date-time and url to uri to fix JSON Schema

### LINKED ISSUE #146: STAC JSON Schema format tags use some invalid values
In https://github.com/radiantearth/stac-spec/blob/master/api-spec/WFS3core%2BSTAC.yaml there is a reference to "dateTime" and "url" string formats

```
type: string
format: dateTime
```

Those should be `date-time` and `uri` to be valid JSON schema.

### PR DESCRIPTION
**Pull request by jasongilman**
Fixes #146

### CODE REVIEW

**Comment by m-mohr** [comment]
I agree with the date-time change, but url was a valid format as of the OpenApi 3 spec (anything is allowed, uri is just an example in the spec). URI is actually more permissive than URL and if URI is intended, the respective descriptions should be changed, too.

**Comment by jasongilman** [comment]
I didn’t realize that about the URL. This pull request should probably be rejected anyway since it was for master instead of dev.

**Comment by m-mohr** [comment]
Oh, that's true. You can close the PR yourself and create a new one... :)

**Comment by cholmes** [comment]
It's an easy drop down to change the PR to be against dev instead. But it looks like it lead to conflicts, though it's just that we remove the swagger2 stuff. So @jasongilman - feel free to close yourself and make a new one, or just clean up your branch for a clean merge.

**Comment by m-mohr** [comment]
I think this issue gets obsolete with #167 anyway. At least I couldn't find any references to dateTime.

**Comment by m-mohr** [comment]
Let's close this, it's fixed by #167.

**Pull request closed without merging**
