### PR TITLE
SAR: incidence_angle, orbits and off_nadir (#405, #423)

### PR DESCRIPTION
**Pull request by m-mohr**
Ad discussed in #405 and #423:
* Added incidence_angle (#405)
* replaced absolute_orbit with relative_orbit (#423)
* redefined off_nadir to suit incidence_angle (#423)

Please review carefully. cc @walterggit @claxn

### CODE REVIEW

**Comment by walterggit** [comment]
@m-mohr @cholmes @claxn : Regarding off-nadir angle, I have never used it for SAR search, and have more commonly seen the incidence angle referenced in the literature that I've read through.  Unless others need it, I think off-nadir angle could be dropped.

For the relative orbit number, the wording is a bit confusing.  The definition of orbit number under https://sentinel.esa.int/web/sentinel/user-guides/sentinel-3-altimetry/definitions/notations matches how I think of relative and absolute orbit numbers, though the reference point for the absolute first orbit and for the first orbit in an orbit cycle may vary with satellite.  The relative orbit number can be useful for finding images with potentially the same viewing geometry. 

Also, I haven't worked with UAVSAR, but looking around a bit, it seems this is an airborne SAR.  Sharing UAVSAR's flightID with satellite SAR orbit numbers in one parameter seems like it is combining two quite different things.  Of the two numbers, I'd say that absolute orbit number is more analogous to flight ID than relative orbit number is, but even that is a stretch.  It would make more sense to me to have flight_id as a separate optional parameter applicable to airborne SAR's.  Is there a plan to differentiate between parameters that are only applicable to airborne versus satellite SARs, or would that be noted in the parameter description?

The observation_direction parameter description looks good to me.

**Comment by claxn** [comment]
The only convenient thing about the off nadir angle is that it is independent from latitude, thus the range of values is fixed for a given observation mode. However, I agree with @walterggit to drop it for now. I am also more used to incidence angles. 

Regarding the orbit numbers I would suggest to keep both. In case these entries should also work with airborne SAR as mentioned by @walterggit we should make it more general. One parameter could be `flight_id` or `track_id` (=absolute orbit number for spaceborne platforms) and an optional parameter `rel_flight_id` or `rel_track_id`.

**Comment by m-mohr** [comment]
Thanks, highly appreciate your feedback @walterggit @claxn .

* I removed off_nadir.
* I re-added absolute_orbit and changed the description of both properties. Still using orbit in the name until we have a consensus to rename them.

Could you please re-review? Thanks!

**Comment by walterggit** [comment]
@m-mohr @claxn : The incidence_angle_center looks good.  

For absolute and relative orbit numbers, I am wondering if it would be better to represent these each with a single value, as with incidence angle.  You don't really gain much by specifying both the start and end orbit numbers, especially since they are almost always identical.  Sentinel-1 defines these values at acquisition start and end; ALOS I think defines a single orbit number at scene center.  It would be a nuisance to extract the metadata if forced to make this anchor point consistent between sensors.  How about something like:

|  sar:relative_orbit  |  number   | A relative orbit number for the acquisition. The relative orbit number is a count of orbits from 1 to the number of orbits contained in a repeat cycle, where relative orbit 1 starts from a defined reference for a given satellite. |

|  sar:orbit_anchor  |  string   | Point in the acquisition that relative and/or absolute orbit numbers are specified for, either 'start', 'center', or 'end'. |

| sar:absolute_orbit    | number | An absolute orbit number for the acquisition. Usually corresponds to the number of orbits elapsed since satellite launch (e.g. ALOS, ERS-1/2, JERS-1, and RADARSAT-1, Sentinel-1). For airborne SAR such as UAVSAR it can be the [Flight ID](http://uavsar.jpl.nasa.gov/cgi-bin/data.pl) or a similar concept. |

Or maybe the anchor could be made part of the relative and absolute orbit definitions themselves (represent with a number and a string instead of just a number).

**Comment by claxn** [comment]
@walterggit: I agree that it is only necessary to have a single value for each orbit number.  I would approve your proposal having those three metadata entries. In my opinion an anchor per orbit number is not necessary, since the numbering of both absolute and relative should follow the same convention.

**Comment by m-mohr** [comment]
@claxn @walterggit I agree with all of your points, except that I don't like the point that a property (orbit_anchor) influences other properties (relative_orbit and absolute_orbit). This makes the latter two not so easily comparable across their range. I'm thinking to follow the thoughts behind the incidence angle and only allow the center. Does that make sense or do you see problems with this approach? I guess, the anchor usually shouldn't change across a collection, but if it does you run into problems when querying as for some results it's then based on start or center or end. That doesn't feel clean and correct. But I'm not sure whether the center can always be computed or retrieved.

**Comment by walterggit** [comment]
@m-mohr @claxn : Sentinel-1 doesn't specify a center orbit number, you'd need to figure it out based on the logic they used to generate the start and end orbit numbers, which is not the job of a metadata extractor.  I do agree that having one parameter influence another could be error prone and unintuitive.  How about dropping the orbit_anchor, but allowing the orbit number to be either the center or start depending on what is available - just call it "orbit number associated with the acquisition" and add a note that this should be the center orbit number if readily available, otherwise the orbit number at the start of the flight?

**Comment by m-mohr** [comment]
Thanks for the quick reply. I think that would work for me, yes. What do you think, @claxn ?

**Comment by claxn** [comment]
@m-mohr @walterggit : Sorry for my late reply. Yes, I agree, this will make things easier! Then we will only have two attributes referring to orbit numbers, which will lead to less confusion at the user side.

**Comment by m-mohr** [comment]
Thanks, I updated the PR accordingly. Feel encouraged to comment if there's still something to improve. Otherwise, I guess we can merge the PR.

**Comment by m-mohr** [comment]
Resolved merge conflicts, we still need a review from a core contributor to be able to merge. @mojodna @matthewhanson ?

**Pull request merged**
