### PR TITLE
Move eo:gsd to gsd

### PR DESCRIPTION
**Pull request by matthewhanson**
**Related Issue(s):** #
#783 

**Proposed Changes:**

gsd (ground sample distance) is a measure of resolution and is applicable to any raster data, not just to the eo extension. 
Moving `eo:gsd` into the Common metadata for items (under the instruments sub-heading) as an optional field for anyone to be able to specify this measure of resolution.

**PR Checklist:**

- [x] This PR is made against the dev branch (all proposed changes except releases should be against dev, not master).
- [ ] This PR has **no** breaking changes.
- [x] I have added my changes to the [CHANGELOG](https://github.com/radiantearth/stac-spec/blob/dev/CHANGELOG.md) **or** a CHANGELOG entry is not required.
- [ ] This PR affects the [STAC API spec](https://github.com/radiantearth/stac-api-spec), and I have opened issue/PR #XXX to track the change.

### CODE REVIEW

**Comment by m-mohr** [comment]
Out of curiosity: Is gsd a term also used in other domains? resolution comes to mind as a broader alternative...

**Comment by jjrom** [comment]
> Out of curiosity: Is gsd a term also used in other domains? resolution comes to mind as a broader alternative...

"resolution" is also the term used in OGC 13-026r8 OpenSearch Extension for Earth Observation (http://docs.opengeospatial.org/is/13-026r8/13-026r8.html)

**Comment by cholmes** [comment]
So I do think there's value in aligning with opensearch for eo. But their structure is more flexible, where you specify the unit (meters, etc) and the value of your gsd. 

My worry about using a more general term would be that other domains define it differently.

**Comment by matthewhanson** [comment]
We've discussed the idea of switching to resolution as the term - but it's a heavily overloaded term, see #672 for explanation and the PR that we closed without merging: #683

**Pull request merged**
