### PR TITLE
Renamed "Scientific Extension" to "Scientific Citation Extension" #990

### PR DESCRIPTION
**Pull request by m-mohr**
**Related Issue(s):** #990

**Proposed Changes:**

1. Renamed "Scientific Extension" to "Scientific Citation Extension", no breaking change (i.e. extension identifier and prefix are not changed)
2. Add Collection Assets to list of "useful" Collection extensions

**PR Checklist:**

- [x] This PR is made against the dev branch (all proposed changes except releases should be against dev, not master).
- [x] This PR has **no** breaking changes.
- [x] I have added my changes to the [CHANGELOG](https://github.com/radiantearth/stac-spec/blob/dev/CHANGELOG.md) **or** a CHANGELOG entry is not required.
- [ ] This PR affects the [STAC API spec](https://github.com/radiantearth/stac-api-spec), and I have opened issue/PR #XXX to track the change.

### CODE REVIEW

**Comment by schwehr** [comment]
+1 for keeping the field names the same. DOIs, publications, and citations are very much a scientific community focused thing.

If there were field changes, it's likely going to be rough going, but not impossible.

Curious if there were any thoughts on what else might go in `sci:`?

**Comment by m-mohr** [comment]
The initial idea was to add reproducibility-related fields, for example, but most have been added to "processing" already.

**Comment by matthewhanson** [comment]
This all looks good to me. I'm approving despite the current failing test.  Not sure what'w causing it, looks like all examples have validated.

**Comment by m-mohr** [comment]
Failing due to #1000

**Review by cholmes — APPROVED** [review]

**Review by jisantuc — APPROVED** [review]
pretty non-controversial 😎

**Pull request merged**
