### PR TITLE
SLD Examples

### PR DESCRIPTION
**Pull request by simonff**
**Related Issue(s):** 916

**Proposed Changes:**

Examples of porting SLD to a STAC extension.
The source of SLD examples under the "SourceUrl" key (which I don't intend to be used in the actual extension)

### CODE REVIEW

**Comment by m-mohr** [comment]
Thanks for going ahead and making a proposal. This seems to be basically a 1:1 mapping from XML to JSON, right? I'm wondering, why do we not just link to the XML?

**Comment by simonff** [comment]
I'm okay with SLD being in an external XML file if everyone else is.

**Comment by cholmes** [comment]
Yeah, I think if we're using SLD it'd make the most sense to just have it as an 'asset' in STAC and link to an external XML file that is actually SLD compliant, instead of porting to JSON. 

We may not even need an extension for this, could just add `application/vnd.ogc.sld+xml` to the table in https://github.com/radiantearth/stac-spec/blob/master/item-spec/item-spec.md#media-types

**Comment by matthewhanson** [comment]
+1 linking to SLD

**Comment by cholmes** [comment]
Closing this, as it should either be a new PR that includes SLD xml as an asset media type, or else a new extension.

**Pull request closed without merging**
