### PR TITLE
Item Properties and Item Asset clarification

### PR DESCRIPTION
**Pull request by philvarner**
**Related Issue(s):** #

**Proposed Changes:**

1. Clarify which objects (e.g., Item Properties or Item Asset) fields apply to
2. Change uses of "Item Assets" to "Item Asset objects" so not to confuse with the item-assets extension (in general, I think we should adopt this style -- instead of pluralizing a STAC type (Type->Types), refer to `Type objects`)

**PR Checklist:**

- [X] This PR is made against the dev branch (all proposed changes except releases should be against dev, not master).
- [X] This PR has **no** breaking changes.
- [X] I have added my changes to the [CHANGELOG](https://github.com/radiantearth/stac-spec/blob/dev/CHANGELOG.md) **or** a CHANGELOG entry is not required.
- [ ] n/a This PR affects the [STAC API spec](https://github.com/radiantearth/stac-api-spec), and I have opened issue/PR #XXX to track the change.

### CODE REVIEW

**Comment by m-mohr** [comment]
Is that a duplicate of #900?

**Comment by philvarner** [comment]
> Is that a duplicate of #900?

I branched it from #900 so it has all those changes too, but it has additional clarifications that may or may not be correct. I'll rebase when #900 is merged for a clean PR.

**Comment by cholmes** [comment]
Ok, #900 us now merged, so you should be good to rebase this one.

**Comment by philvarner** [comment]
h/t to @vpipkt for bringing up the need to clarify these fields

**Review by jisantuc — APPROVED** [review]
Good from me. This kind of change makes me curious about whether there's a latent schema that applies to extensions. Discovering that schema would be a boon to downstream extension implementers / parsers (at least it would be a boon to stac4s)

**Comment by m-mohr** [comment]
> whether there's a latent schema that applies to extensions.

What is a latent schema? What exactly are you looking for?

**Review by m-mohr — APPROVED** [review]

**Comment by m-mohr** [comment]
Approving, but CI fails, which needs to be fixed before the merge.

**Pull request merged**
