### PR TITLE
add additional text for calculating center_wavelengt and full_width_h…

### PR DESCRIPTION
**Pull request by matthewhanson**
**Related Issue(s):** #
#979 

**Proposed Changes:**

1. Add text to go from min/max wavelengths to center_wavelength and full_width_half_max

**PR Checklist:**

- [x] This PR is made against the dev branch (all proposed changes except releases should be against dev, not master).
- [x] This PR has **no** breaking changes.
- [x] I have added my changes to the [CHANGELOG](https://github.com/radiantearth/stac-spec/blob/dev/CHANGELOG.md) **or** a CHANGELOG entry is not required.
- [ ] This PR affects the [STAC API spec](https://github.com/radiantearth/stac-api-spec), and I have opened issue/PR #XXX to track the change.

### CODE REVIEW

**Comment by cholmes** [comment]
This is a good start, but still not enough for me as a non-remote-sensing expert to know what to do. Am I allowed to just assume it's a 'top-hat' filter? Or am I supposed to go ask some expert to figure out if it is actually a top-hat? I'm pretty sure Planet's is not a top hat... (I did get the fwhm for at least skysat, so this isn't pressing for me, just want it to be easier for whoever comes next) And it would probably be good to have an example conversion too.

**Comment by matthewhanson** [comment]
You're right it's not really clear.  In reality, there's no such thing as a top-filter, it's only a theoretical concept and an approximation in the absence of a full spectral transmission profile.  But if all you have is min and max, you can convert that to center and fwhm, but that is also an approximation. 

These numbers are helpful to determine the approximate location (color) of a band, but if you actually needed it for analysis/pre-processing (especially required in harmonization between sensors), then you'd want the complete profile.  As an aside, the spectral profile can shift over time as well. They are usually characterized before launch.

I'll update to make it simpler, provide an example, but also want to make it clear these are approximate characterizations.

**Comment by cholmes** [comment]
Sounds great - that's exactly what I'd want to see. 

That reminds me, the other note that we should add is to encourage people to use the 'common names' even if they don't have center wavelength and full width half max. That came up with NAIP, and I hadn't actually known to do that. I see the value, but the eo extension doesn't come right out and say it (though they aren't required).

**Comment by kylebarron** [comment]
> encourage people to use the 'common names' even if they don't have center wavelength and full width half max

Big +1. It makes it a lot easier to interpret the data if you can look at `common_name` instead of parsing the wavelength, and `common_name` without wavelength/width vastly improves ease of use of the image.

**Review by lossyrob — APPROVED** [review]

**Review by cholmes — APPROVED** [review]

**Pull request merged**
