### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by jbants**
replace 404 link for projjson

**Related Issue(s):** #
None

**Proposed Changes:**

1. Replace projjson link

**PR Checklist:**

- [x ] This PR has **no** breaking changes.
- [ ] I have added my changes to the [CHANGELOG](https://github.com/radiantearth/stac-spec/blob/dev/CHANGELOG.md) **or** a CHANGELOG entry is not required.
- [ ] API only: I have run `npm run generate-all` to update the [generated OpenAPI files](https://github.com/radiantearth/stac-spec/blob/dev/api-spec/README.md#openapi-definitions).

### CODE REVIEW

**Comment by cholmes** [comment]
@m-mohr - I changed it to dev, should be good to merge.

**Comment by m-mohr** [comment]
I just saw: The PROJJSON links in /extensions/datacube/README.md are also broken, unfortunately.

**Comment by m-mohr** [comment]
Good, can be merged. Are there any occurances of this in API spec?

**Comment by cholmes** [comment]
A quick check looks like no occurrences in the API spec

**Pull request merged**
