### PR TITLE
Summaries in catalogs

### PR DESCRIPTION
**Pull request by cholmes**
**Related Issue(s):** #903 #822

**Proposed Changes:**

1. Moved summaries from collection spec to catalog spec
2.  Had to do a minor bit on #822 so that I could link easily between the two. 

**PR Checklist:**

- [x] This PR is made against the dev branch (all proposed changes except releases should be against dev, not master).
- [x] This PR has **no** breaking changes.
- [x] I have added my changes to the [CHANGELOG](https://github.com/radiantearth/stac-spec/blob/dev/CHANGELOG.md).

### CODE REVIEW

**Comment by m-mohr** [comment]
I'm not a fan of this at all and won't approve. For me summaries is fundamental for collections and catalogs is just a "side" use case that no body has ever implemented yet. Thus, I'm not a fan to make it less visible in Collections and hide important details about summaries in Catalogs.

**Comment by cholmes** [comment]
Ok. I don't feel strongly, just was going for not repeating things. I agree collections is the 'main' use case.

What about having the text in collections and linking to that from catalogs? So it appears in the primary place, but catalogs has a line that mentions summaries can be used there? Like just flip it around from how I proposed?

**Comment by m-mohr** [comment]
That would work for me.

**Comment by cholmes** [comment]
Ok, this should be ready to go. Please approve if it works.

**Review by matthewhanson — APPROVED** [review]

**Review by m-mohr — APPROVED** [review]
LGTM

**Pull request merged**
