### PR TITLE
Projection doc fix

### PR DESCRIPTION
**Pull request by davidraleigh**
**Related Issue(s):** #
None

**Proposed Changes:**

1. Update broken link for `proj:projjson`
2.  Update to CONTRIBUTING.md to allow for using Docker instead of installing npm locally

**PR Checklist:**

- [x] This PR is made against the dev branch (all proposed changes except releases should be against dev, not master).
- [x] This PR has **no** breaking changes.
- [X] I have added my changes to the [CHANGELOG](https://github.com/radiantearth/stac-spec/blob/dev/CHANGELOG.md) **or** a CHANGELOG entry is not required.
- [ ] This PR affects the [STAC API spec](https://github.com/radiantearth/stac-api-spec), and I have opened issue/PR #XXX to track the change.

### CODE REVIEW

**Comment by davidraleigh** [comment]
@m-mohr small docs fix for projection

**Comment by m-mohr** [comment]
@davidraleigh The link is not broken for me and I think it's better to link to the HTML description page rather than linking to the JSON Schema.

**Review by m-mohr — CHANGES_REQUESTED** [review]
@davidraleigh The link is not broken for me and I think it's better to link to the HTML description page rather than linking to the JSON Schema.

I can't run Docker, so I can't test, but it looks like it would only run on *nix systemns with that command. We should add a note or provide it platform independant.

**Comment by davidraleigh** [comment]
@m-mohr it looks like dev used to have the old https://proj.org/usage/projjson.html link when I made this change. Now that it's https://proj.org/specifications/projjson.html, it's totally fine

**Pull request closed without merging**
