### PR TITLE
[WIP] Validate examples

### PR DESCRIPTION
**Pull request by lossyrob**
**Related Issue(s):** #632 

**Proposed Changes:**

1. Add a validation script that validates all examples in the repository.
2. Fix up examples that did not pass validation.

Work in progress for the moment. I will cherry-pick changes on top of dev after #640 is merged.

**PR Checklist:**

- [x] This PR has **no** breaking changes.
- [ ] I have added my changes to the [CHANGELOG](https://github.com/radiantearth/stac-spec/blob/dev/CHANGELOG.md) **or** a CHANGELOG entry is not required.
- [ ] API only: I have run `npm run generate-all` to update the [generated OpenAPI files](https://github.com/radiantearth/stac-spec/blob/dev/api-spec/README.md#openapi-definitions).

### CODE REVIEW

**Comment by matthewhanson** [comment]
Talked with @jbants , sounds like this needs some more work so won't be ready for 0.9.0 release, moving to 1.0

**Comment by lossyrob** [comment]
Sounds good; I should have some time in the next couple of weeks to update and clean this up.

**Comment by cholmes** [comment]
What's the state of this? Possible to get done for 1.0-beta1?

**Comment by lossyrob** [comment]
Closing in favor of #834

**Pull request closed without merging**
