### PR TITLE
Specify how to read no URL proprietary license

### PR DESCRIPTION
**Pull request by jisantuc**
**Related Issue(s):** #664

**Proposed Changes:**

1. Explicitly state the interpretation of absence of URL when `license` on collections is proprietary

**PR Checklist:**

- [x] This PR has **no** breaking changes.
- [x] I have added my changes to the [CHANGELOG](https://github.com/radiantearth/stac-spec/blob/dev/CHANGELOG.md) **or** a CHANGELOG entry is not required.
- ~API only: I have run `npm run generate-all` to update the [generated OpenAPI files](https://github.com/radiantearth/stac-spec/blob/dev/api-spec/README.md#openapi-definitions).~

### CODE REVIEW

**Comment by matthewhanson** [comment]
Thanks for the PR @jisantuc , can you update it to be against the `dev` branch rather than `master`?

**Comment by jisantuc** [comment]
It is done -- I went looking for previous chatter about the default branch, is there any particular reason to keep it `master` instead of `dev`, if `dev` is what PRs should target?

**Comment by m-mohr** [comment]
Looks good, with the exception that in the Collection the addition is in the link rel types. In the Item it is in the Field Description and in the Collection it should also be described there instead of in the link rel type, I think.

**Comment by matthewhanson** [comment]
@jisantuc the idea is that the `master` branch is the last released version, so is the branch that people see when they come to the page, while `dev` is the current (under development) version.  PRs should always target `dev`.

**Comment by m-mohr** [comment]
Looks good, thanks. I added a Changelog entry for you.

**Pull request merged**
