### PR TITLE
Fix EO example

### PR DESCRIPTION
**Pull request by m-mohr**
**Related Issue(s):** None (but let's celebrate PR/issue #1000) ✨

**Proposed Changes:**

1. Not exactly sure how it happened, but the EO example got corrupted. (edit: It was a bug in stac-node-validator)

**PR Checklist:**

- [x] This PR is made against the dev branch (all proposed changes except releases should be against dev, not master).
- [x] This PR has **no** breaking changes.
- [x] I have added my changes to the [CHANGELOG](https://github.com/radiantearth/stac-spec/blob/dev/CHANGELOG.md) **or** a CHANGELOG entry is not required.
- [ ] This PR affects the [STAC API spec](https://github.com/radiantearth/stac-api-spec), and I have opened issue/PR #XXX to track the change.

### CODE REVIEW

**Comment by cholmes** [comment]
Hrm, I think this will be a conflict with #955 as I got rid of this example. I'll approve, but would probably prefer to just delete it so I don't have to resolve the conflict on that merge.

**Review by cholmes — APPROVED** [review]

**Comment by cholmes** [comment]
And awesome work everyone on #1000!

**Comment by m-mohr** [comment]
Okay, let's wait with this until #955 gets merged (or rejected) and then act accordingly here - unfortunately then all PRs until the merge if #955 will likely "break" as the CI will report an invalid example now that I've fixed the bug in STAC Node validator.

**Comment by cholmes** [comment]
We could run the check with the fix on the refresh-examples branch?

**Comment by m-mohr** [comment]
I don't understand your last comment. On the other hand, we could just merge and then I'll resolve the conflict. That should be easy as the file got deleted in #955.

**Comment by m-mohr** [comment]
I've merged this into the examples refresh PR so that it doesn't give merge conflicts. So in the meantime it would be great to merge this so that the CI in PRs is not failing. Could someone approve? @matthewhanson @jbants

**Review by jisantuc — APPROVED** [review]

**Pull request merged**
