### PR TITLE
Fixing alignment issues with OGC API - Features and STAC API. #616

### PR DESCRIPTION
**Pull request by m-mohr**
**Related Issue(s):** #616, partially #454 

**This PR needs careful reviews to not screw it up again. The changes are not easy to make/maintain due to the merging procedure in place. Also, OpenAPI tooling differs. I strongly recommend to not only review the changes in the files, but also load the OpenAPI files into ReDoc (e.g. [STAC with extensions](http://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/radiantearth/stac-spec/stac-api-fixes/api-spec/STAC-extensions.yaml)) and review the rendered version!**

**Proposed Changes:**

1. Trying to fix the issue that the STAC API did not render any STAC specifics in the OAF endpoints
2. Trying to fix issues with examples

**PR Checklist:**

- [ ] This PR has **no** breaking changes.
- [x] I have added my changes to the [CHANGELOG](https://github.com/radiantearth/stac-spec/blob/dev/CHANGELOG.md) **or** a CHANGELOG entry is not required.
- [x] API only: I have run `npm run generate-all` to update the [generated OpenAPI files](https://github.com/radiantearth/stac-spec/blob/dev/api-spec/README.md#openapi-definitions).

### CODE REVIEW

**Comment by cholmes** [comment]
This is definitely a pain to review + suggest changes. There's a little typo 'linkto' instead of 'link to' - https://github.com/radiantearth/stac-spec/blob/a405f61fbbc8fbd670f4450b1376d02c237224f4/api-spec/STAC-extensions.yaml#L2094

And it's a same error in the OAFeat repo - https://github.com/opengeospatial/ogcapi-features/blob/b4a51a6adcc675e0772c677190075853c14042cd/core/openapi/ogcapi-features-1.yaml#L690 And I'm not even sure if that's the source, or if there's another file that's generated from :(

**Comment by m-mohr** [comment]
The file is correct: https://github.com/opengeospatial/ogcapi-features/pull/280

Will also change it here...

**Comment by cholmes** [comment]
Awesome, thanks!

**Comment by matthewhanson** [comment]
For the STAC-extensions.yaml file when rendered in swagger, the query parameter string is truncated, and there's no link to to the queryFilter schema which seems like it should.
image

The query schema says 'string',  but should it reference queryFilter isntead?
https://github.com/radiantearth/stac-spec/blob/stac-api-fixes/api-spec/extensions/query/query.fragment.yaml#L8

**Pull request merged**
