### PR TITLE
Move label:classes to be a list of classes.

### PR DESCRIPTION
**Pull request by lossyrob**
**Related Issue(s):** #578

**Proposed Changes:**

Move `label:classes` property to be a list of class objects.

**PR Checklist:**

- [x] This PR has **no** breaking changes.
- [x] I have added my changes to the [CHANGELOG](https://github.com/radiantearth/stac-spec/blob/dev/CHANGELOG.md) **or** a CHANGELOG entry is not required.
- [x] API only: I have run `npm run generate-all` to update the [generated OpenAPI files](https://github.com/radiantearth/stac-spec/blob/dev/api-spec/README.md#openapi-definitions).

### CODE REVIEW

**Comment by lossyrob** [comment]
I'm unclear on if this needs a CHANGELOG entry - if so let me know and I'll add it.

**Comment by m-mohr** [comment]
This must be included in 0.8. This just fixes what the examples already show: label:classes is an array. Not having this in 0.8 either leaves us with an invalid schema/spec Or invalid examples.

**Comment by cholmes** [comment]
Ah, gotcha. If that's the case then I think we can just consider it a 'fix' and not have to do another release candidate.

**Comment by lossyrob** [comment]
@cholmes Sorry for the incorrect base, I thought I made it off of dev... :shrug:

The 0.8.0-RC1 release notes have the label extension as 'added'; a 'fixed' changelog entry would make sense if there was a new RC, but if we aren't making another RC for this fix, it might not make sense to have both an 'added' and 'fixed' lines in the changelog for the same feature. But I can put one in if you still think it makes sense, or else I'll merge away.

**Comment by m-mohr** [comment]
It could be added as "fixed" for 0.8.0. "Added" was 0.8.0-rc.1.

**Comment by lossyrob** [comment]
@m-mohr Added changelog entry to the `unreleased` section of the CHANGELOG, which can be moved to 0.8.0 once it moves out of release candidate. If that seems good, looks good to merge - from a process standpoint, should I merge this PR or will one of you?

**Comment by lossyrob** [comment]
From gitter conversation, this is good to go.

**Pull request merged**
