### PR TITLE
Updated UML to 0.9.0

### PR DESCRIPTION
**Pull request by hgs-msmith**
**Related Issue(s):** #566

**Proposed Changes:**
Updated UML diagram to reflect 0.9.0 changes

**PR Checklist:**
- [X] This PR has **no** breaking changes.

### CODE REVIEW

**Comment by anayeaye** [comment]
Noticed one tiny thing: eo:platform has been removed from the eo extension

**Comment by cholmes** [comment]
@anayeaye - I just updated to remove platform. Could you check it to make sure I did it right?

**Comment by m-mohr** [comment]
Seems correct. I'd remove the EO extension though. It's a bit strange why EO is in and SAT for example is not.

**Comment by cholmes** [comment]
Ah, good point. Will remove it.

**Comment by m-mohr** [comment]
Great, sorry for not seeing this all at the same time, but title got moved to common metadata...

**Comment by cholmes** [comment]
No prob - appreciate them flowing fast, as I've got the draw.io open on a tab, so it's easy to update.

**Comment by m-mohr** [comment]
Also, the ItemCollection is not included, but I guess that's fine. So approving now.

**Pull request merged**
