### PR TITLE
ETag support for optimistic locking + add transaction extension to STAC-extensions.yaml

### PR DESCRIPTION
**Pull request by hgs-truthe01**
While using the transactions extension we discovered some issues with concurrent changes to the documents. I wanted to propose using the ETag header to support optimistic locking to prevent changes from stepping on each other.

In this proposal, the PATCH call doesn't require a ETAG, but optionally supports one. Since it isn't replacing the whole document and is making specific changes I think that makes sense. PUT should require it though.

### CODE REVIEW

**Comment by hgs-truthe01** [comment]
Also, I want to mention that I ran all of the generate scripts, so there are some changes that are not part of this PR that ended up in the generated files. I'm not sure if it is better to get everything synced up in this PR or restrict it to just my changes.

**Comment by m-mohr** [comment]
> Also, I want to mention that I ran all of the generate scripts, so there are some changes that are not part of this PR that ended up in the generated files.

You could review #532, merge it in dev and here, and then this should fix stuff here.

I'll have a look at this PR tomorrow.

**Comment by hgs-truthe01** [comment]
Thanks for the help on the cleanup @m-mohr !

**Comment by cholmes** [comment]
Just reviewed and merged #538 as I saw this go by on my email.

**Comment by m-mohr** [comment]
Great, will resolve conflicts later and merge.

**Comment by m-mohr** [comment]
**PR checklist:**

- [x] This PR has breaking changes.
- [ ] I have added my changes to the [CHANGELOG](https://github.com/radiantearth/stac-spec/blob/dev/CHANGELOG.md).
- [x] API only: I have updated the [generated OpenAPI files](https://github.com/radiantearth/stac-spec/blob/dev/api-spec/README.md#openapi-definitions) by executing `npm run generate-all`.

**Pull request merged**
