### PR TITLE
JSON Schemas, Validation and CI

### PR DESCRIPTION
**Pull request by m-mohr**
**Related Issue(s):** #835

**Proposed Changes:**

1. Add unique/resolvable JSON Schema ids
2. Allow schema urls in stac_extenions
3. Remove validation instructions
4. Adapt CI to host JSON Schemas

Open questions:
1. ~Schemas for the dev branch only work when we replace all version numbers in the schemas with dev and then on each release replace dev with the version number again. Is that worth the hassle?~ Yes, we do replace dev with the version number, added to process.md
2. ~Is it confusing that I removed json-schema from the paths? Feels a bit cleaner.~ added json-schema back to the path
3. ~Due to 2, the $refs are now all absolute instead of relative. Is that okay?~ relative again
4. ~It seems I couldn't make the deploy key working properly. Can anyone assist? It works locally with username and password...~ Solved
5. ~Why is the CI job running for PRs?~ Solved

~ToDo for @cholmes: Setup schemas.stacspec.org and add the CNAME file to the repo.~

**PR Checklist:**

- [x] This PR is made against the dev branch (all proposed changes except releases should be against dev, not master).
- [x] This PR has **no** breaking changes.
- [x] I have added my changes to the [CHANGELOG](https://github.com/radiantearth/stac-spec/blob/dev/CHANGELOG.md) **or** a CHANGELOG entry is not required.
- [ ] This PR affects the [STAC API spec](https://github.com/radiantearth/stac-api-spec), and I have opened issue/PR #XXX to track the change.

### CODE REVIEW

**Comment by m-mohr** [comment]
It's the file name. I don't think that's an issue as the other parts of the URL (extension folder) will make the $id unique, e.g. `https://stacspec.org/schemas/v1.0.0-beta.1/extensions/label/schema.json#`

**Comment by cholmes** [comment]
http://schemas.stacspec.org is set up and looks to be working.

**Comment by m-mohr** [comment]
Great, thanks. Now we need to discuss the open questions (see first post)

**Comment by m-mohr** [comment]
Updated PR, two CI issues to be fixed, but need help with them.

**Comment by m-mohr** [comment]
So, it should work now. Still need to check again whether I can make my node validator work with the new schemas, but other than that, this PR is finished.

**Comment by m-mohr** [comment]
The validator works as expected, everything seems to be valid. Only need another approval for the PR.

**Pull request merged**
