### PR TITLE
Added the derived_from relation

### PR DESCRIPTION
**Pull request by cholmes**
See #179 

We likely should also create an extension that more fully spells out some of the ideas for this field, as well as additions to make the links more useful. Like explain that it could be used to link to non-STAC metadata, etc. But wanted to get this in so people could start to use it.

### CODE REVIEW

**Comment by cholmes** [comment]
@omad - your review on this would be great too.

**Comment by m-mohr** [comment]
I'd recommend to add this also to datasets and catalogs. They could also be derived from anothet dataset / catalog.

**Comment by cholmes** [comment]
@m-mohr - just added it in, but I'm not sure if I really love it. I said that you could derived a dataset / catalog from an Item as well. But then I wonder if it's a bit too flexible... Like if we limit it to just being derived from an Item then someone who follows the rel link can expect an Item. And more Items can be handled with more links. 

And then the case where an Item is derived_from a catalog: In the case of a mosaic that points to a catalog of exactly the items that make it up that makes sense to me. But I fear it'll often be used to just point at a dataset that would have lots of data that isn't actually used. So it'd become more meaningless.

So I think I actually want to start with just having derived_from in Item. I'm totally cool if people reuse it in dataset / catalog, but I don't want it to be so broadly defined.

If you do really want to use it for datasets the one thing I could go for is only including it in dataset, and defining it to only be pointing at other datasets. So basically the relation would be in context - a dataset can be derived_from a dataset, and an Item can be derived_from an Item. And I'm inclined to leave off Catalog, as I don't really know the use case.

**Comment by m-mohr** [comment]
Sorry, that is a misunderstanding. Items should only be derived from items as you said! But datasets could be derived from other datasets, so that spec should also allow that. So I just wanted to get in what you explained on

**Comment by cholmes** [comment]
Ok @m-mohr - made the changes, I think everything is good for review now, thanks!

**Comment by m-mohr** [comment]
We need another reviewer with write access as @omad s review doesn't count towards the 2 approving requests as he has no write access to the repo.

**Pull request merged**
